/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EditPost: typeof import('./components/EditPost.vue')['default']
    Posts: typeof import('./components/Posts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPosts: typeof import('./components/SearchPosts.vue')['default']
  }
}
